version: '3.8'
services:

  user-db:
    image: mysql:8.0
    container_name: user-db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: user_db
    ports:
      - "3307:3306"

  activity-db:
    image: mysql:8.0
    container_name: activity-db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: activity
    ports:
      - "3308:3306"
  newsfeed-db:
    image: mysql:8.0
    container_name: newsfeed-db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: newsfeed
    ports:
      - "3309:3306"
  product-db:
    image: mysql:8.0
    container_name: product-db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: product
    ports:
      - "3310:3306"

  redis:
    container_name: redis-db
    image: redis
    ports:
      - "6379:6379"


  discovery-service:
    image: ekek0329/discovery-service:0.0.1
    ports:
      - "8761:8761"


